config/routes.rb
Rails.application.routes.draw do

  namespace :api, path: "api" do
    namespace :v1 do
      resources :districts, only: [:index] do
        resources :schools, only: [:index] do
          resources :campaigns, only: [:index]
        end
      end
      resources :schools, only: [] do
        resources :teachers, only: [:index]
      end
    end
  end

  constraints(subdomain: /master/) do
    devise_for :users, path: 'u', controllers: { sessions: "master/sessions" }

    namespace :master_ajax do
      resources :schools, only: [] do
        resources :campaigns, only: [:new, :create], to: 'schools/campaigns'
      end

      resources :teachers, only: [] do
        resources :campaigns, only: [:new, :create], to: 'teachers/campaigns'
      end
    end

    scope module: 'master' do
      resources :users
      resources :products

      resources :states do
        resources :districts
      end

      resources :districts, only: [] do
        resources :schools
      end

      resources :schools do
        resources :teachers do
          member do
            match :reassign, via: [:get, :post]
          end
        end
      end

      resources :campaigns, param: 'slug', except: [:new, :create] do
        resources :impressions
      end

      resources :imports, only: [] do
        collection do
          match :schools, via: [:get, :post]
          match :indiegogo, via: [:get, :post]
        end
      end

      resources :contributors
      resources :contributions
      resource :tos, only: [:show, :edit, :update]

      resources :searches, only: [:index]

      resources :reports, only: [:index] do
        collection do
          match :pending_impressions, via: [:get]
        end
      end

      resources :campaign_requests, except: [:new, :create], param: 'slug' do
        member do
          match :convert, via: [:get, :post]
        end
      end

      match '/', to: 'campaigns#index', via: [:get], as: :master_root
    end
  end

  constraints(subdomain: /landing/) do
    resources :schools, only: [] do
      resources :teachers, only: [:new, :create]
    end

    resources :campaigns, only: [], param: 'slug' do
      collection do
        match :new, via: [:get], as: :landing_new, path: 'new'
        match :create, via: [:post]
      end
      member do
        match :show, via: [:get], as: :landing
        match :partner, via: [:get]
        match :reports, via: [:get]
        match :contributions, via: [:get]
        match :thank_you, via: [:get, :post]
      end
      resources :impressions, only: [:create], as: :landing_impressions
    end

    resources :campaign_requests, only: [:new, :create], param: 'slug'
    resources :campaign_requests, only: [], param: 'slug' do
      member do
        match :show, via: [:get], as: :landing
      end
    end
  end

  root 'public#index'

end

app/controllers/api/v1/teachers_controller.rb
class Api::V1::TeachersController < ApiController
  before_action :load_school

  respond_to :json

  def index
    @teachers = @school.teachers.ordered

    # Scope this
    if params.try(:[], :scoped).present?
      @teachers = @teachers.with_campaigns
    end

    respond_to do |format|
      format.html { render text: "Format not supported!" }
      format.json { render json: @teachers.to_json }
    end
  end


  private

  def load_school
    @school = School.find(params[:school_id])
  end

end

app/controllers/master/campaign_requests_controller.rb
class Master::CampaignRequestsController < MasterController

  before_action :set_campaign_request, only: [:show, :edit, :update, :destroy, :convert]
  before_action :check_approved_at, only: [:edit, :update, :convert]

  def index
    @campaign_requests = CampaignRequest.not_approved.ordered.page(params[:page])
  end

  def show
  end

  def edit
  end

  def update
    if @campaign_request.update(safe_params)
      redirect_to @campaign_request, notice: 'Campaign Request was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @campaign_request.destroy
    redirect_to campaign_requests_url, notice: 'Campaign Request was successfully removed.'
  end

  def convert
    if request.post?
      if @campaign_request.convert(convert_params)
        redirect_to campaign_requests_url, notice: 'Campaign Request was successfully converted.'
      else
        render :convert
      end
    else
      # GET stuff here
    end
  end


  private

  def check_approved_at
    if @campaign_request.approved_at.present?
      flash[:error] = 'Cannot modify approved Campaign Requests!'
      redirect_to campaign_requests_path
    end
  end

  def set_campaign_request
    @campaign_request = CampaignRequest.find_by(slug: params[:slug])
  end

  def safe_params
    safe_attributes = [
      :campaign_name,
      :district_name,
      :email,
      :physical_address,
      :physical_address_ext,
      :physical_city,
      :physical_postal_code,
      :physical_state,
      :product_id,
      :school_name,
      :school_wide,
      :state_id,
      :teacher_first_name,
      :teacher_last_name,
    ]
    params.require(:campaign_request).permit(safe_attributes)
  end

  def convert_params
    safe_attributes = [
      :campaign_name,
      :district_name,
      :email,
      :physical_address,
      :physical_address_ext,
      :physical_city,
      :physical_postal_code,
      :physical_state,
      :product_id,
      :school_name,
      :school_wide,
      :state_id,
      :teacher_first_name,
      :teacher_last_name,
      associations: [
        :district_id,
        :school_id,
        :teacher_id,
      ]
    ]
    params.require(:convert_campaign_request).permit(safe_attributes)
  end

end

app/controllers/master/campaigns_controller.rb
class Master::CampaignsController < MasterController
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]

  def index
    @campaigns = Campaign.all
    @teacher_campaigns = @campaigns.teacher_based
    @school_campaigns = @campaigns.school_based

    # Search based on my criteria
    if params[:search].try(:[], :query).present?
      @teacher_campaigns = @teacher_campaigns.search(params[:search][:query])
      @school_campaigns = @school_campaigns.search(params[:search][:query])
    end

    # Order by Sorty Params
    if params[:search].try(:[], :sorty).present?
      @teacher_campaigns = @teacher_campaigns.sorty_order(sort_column, sort_direction)
      @school_campaigns = @school_campaigns.sorty_order(sort_column, sort_direction)
    else
      @teacher_campaigns = @teacher_campaigns.ordered
      @school_campaigns = @school_campaigns.ordered
    end

    # Paginate them
    @teacher_campaigns = @teacher_campaigns.page(params[:teachers_page])
    @school_campaigns = @school_campaigns.page(params[:schools_page])
  end

  def show
    @contributions = @campaign.contributions.ordered.page(params[:contributions_page])
    @impressions = @campaign.impressions.ordered.page(params[:impressions_page])
  end

  def edit
  end

  def update
    if @campaign.update(safe_params)
      redirect_to @campaign, notice: 'Campaign was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @campaign.destroy
    redirect_to campaigns_url, notice: 'Campaign was successfully removed.'
  end


  private

  def set_campaign
    @campaign = Campaign.find_by(slug: params[:slug])
  end

  def safe_params
    safe_attributes = [
      :active,
      :campaignable_id,
      :campaignable_type,
      :district_id,
      :goal_amount_dollars,
      :name,
      :product_id,
      :school_id,
      :state_id,
      :physical_address,
      :physical_address_ext,
      :physical_city,
      :physical_state,
      :physical_postal_code,
    ]
    params.require(:campaign).permit(safe_attributes)
  end

end

app/controllers/master/contributions_controller.rb
class Master::ContributionsController < MasterController
  before_action :set_contribution, only: [:show, :edit, :update, :destroy]

  def index
    @contributions = Contribution.all
    @contributions = @contributions.search(params[:search][:query]) if params[:search].try(:[], :query).present?
    if params[:search].try(:[], :sorty).present?
      @contributions = @contributions.sorty_order(sort_column, sort_direction)
    else
      @contributions = @contributions.ordered
    end
    @contributions = @contributions.page(params[:page])
  end

  def show
  end

  def new
    @contribution = Contribution.new
  end

  def edit
  end

  def create
    @contribution = Contribution.new(safe_params)

    if @contribution.save
      redirect_to @contribution, notice: 'Contribution was successfully created.'
    else
      render :new
    end
  end

  def update
    if @contribution.update(safe_params)
      redirect_to @contribution, notice: 'Contribution was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @contribution.destroy
    redirect_to contributions_url, notice: 'Contribution was successfully removed.'
  end


  private

  def set_contribution
    @contribution = Contribution.find(params[:id])
  end

  def safe_params
    params.require(:contribution).permit(:pledge_id, :pledged_at, :contributor_id, :campaign_id, :amount_dollars)
  end

end

app/controllers/master/contributors_controller.rb
class Master::ContributorsController < MasterController
  before_action :set_contributor, only: [:show, :edit, :update, :destroy]

  def index
    @contributors = Contributor.all
    @contributors = @contributors.search(params[:search][:query]) if params[:search].try(:[], :query).present?
    if params[:search].try(:[], :sorty).present?
      @contributors = @contributors.sorty_order(sort_column, sort_direction)
    else
      @contributors = @contributors.ordered
    end
    @contributors = @contributors.page(params[:page])
  end

  def show
    @contributions = @contributor.contributions.ordered.page(params[:page])
  end

  def new
    @contributor = Contributor.new
  end

  def edit
  end

  def create
    @contributor = Contributor.new(contributor_params)

    if @contributor.save
      redirect_to @contributor, notice: 'Contributor was successfully created.'
    else
      render :new
    end
  end

  def update
    if @contributor.update(contributor_params)
      redirect_to @contributor, notice: 'Contributor was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @contributor.destroy
    redirect_to contributors_url, notice: 'Contributor was successfully removed.'
  end


  private

  def set_contributor
    @contributor = Contributor.find(params[:id])
  end

  def contributor_params
    params.require(:contributor).permit(:name, :email)
  end

end

app/controllers/master/districts_controller.rb
class Master::DistrictsController < MasterController
  before_action :set_state
  before_action :set_district, only: [:show, :edit, :update, :destroy]

  def index
    @districts = @state.districts
    @districts = @districts.search(params[:search][:query]) if params[:search].try(:[], :query).present?
    if params[:search].try(:[], :sorty).present?
      @districts = @districts.sorty_order(sort_column, sort_direction)
    else
      @districts = @districts.ordered
    end
    @districts = @districts.page(params[:page])
    @campaigns = @state.campaigns.ordered.page(params[:campaigns_page])
  end

  def show
    @schools = @district.schools.ordered.page(params[:schools_page])
    @campaigns = @district.campaigns.ordered.page(params[:campaigns_page])
  end

  def new
    @district = @state.districts.new
  end

  def edit
  end

  def create
    @district = @state.districts.new(safe_params)

    if @district.save
      redirect_to state_district_url(@state, @district), notice: 'District was successfully created.'
    else
      render :new
    end
  end

  def update
    if @district.update(safe_params)
      redirect_to state_district_url(@state, @district), notice: 'District was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @district.destroy
    redirect_to state_districts_url(@state), notice: 'District was successfully removed.'
  end


  private

  def set_state
    @state = State.find_by(abbr: params[:state_id])
  end

  def set_district
    @district = @state.districts.find(params[:id])
  end

  def safe_params
    params.require(:district).permit(:name, :state_id)
  end

end

app/controllers/master/imports_controller.rb
class Master::ImportsController < MasterController

  def schools
    if request.post?
      result = Import.import_schools(safe_params.try(:[], :file))
      if result[:success]
        flash[:notice] = "Successfully imported stuff, count: #{result.try(:[], :count)}"
      else
        flash[:error] = "Failed to import: #{result.try(:[], :message)}"
      end
      redirect_to schools_imports_url
    else
      # GET stuff here
    end
  end

  def indiegogo
    if request.post?
      result = Import.import_indiegogo_data(safe_params.try(:[], :file))
      if result[:success]
        flash[:notice] = "Successfully imported indiegogo data, count: #{result.try(:[], :count)}"
      else
        flash[:error] = "Failed to import: #{result.try(:[], :message)}"
      end
      redirect_to indiegogo_imports_url
    else
      # GET stuff here
    end
  end


  private

  def safe_params
    safe_attributes = [:file]
    params.require(:imports).permit(safe_attributes)
  end

end

app/controllers/master/impressions_controller.rb
class Master::ImpressionsController < MasterController
  before_action :set_campaign
  before_action :set_impression, only: [:show, :edit, :update, :destroy]

  def index
    @impressions = @campaign.impressions.ordered.page(params[:page])
    @contributions = @campaign.contributions.ordered.page(params[:contributions_page])
  end

  def show
  end

  def new
    @impression = @campaign.impressions.new
  end

  def edit
  end

  def create
    @impression = @campaign.impressions.new(safe_params)

    if @impression.save
      redirect_to campaign_impressions_url(@campaign.to_param), notice: 'Impression was successfully created.'
    else
      render :new
    end
  end

  def update
    if @impression.update(safe_params)
      redirect_to campaign_impressions_url(@campaign.to_param), notice: 'Impression was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @impression.destroy
    redirect_to campaign_impressions_url(@campaign.to_param), notice: 'Impression was successfully removed.'
  end


  private

  def set_campaign
    @campaign = Campaign.find_by(slug: params[:campaign_slug])
  end

  def set_impression
    @impression = @campaign.impressions.find(params[:id])
  end

  def safe_params
    safe_attributes = [:email, :campaign_id, :referral_kind, :token]
    params.require(:impression).permit(safe_attributes)
  end

end

app/controllers/master/products_controller.rb
class Master::ProductsController < MasterController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
    @products = @products.search(params[:search][:query]) if params[:search].try(:[], :query).present?
    if params[:search].try(:[], :sorty).present?
      @products = @products.sorty_order(sort_column, sort_direction)
    else
      @products = @products.ordered
    end
    @products = @products.page(params[:page])
  end

  def show
    @campaigns = @product.campaigns.ordered.page(params[:campaigns_page])
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(safe_params)

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  def update
    if @product.update(safe_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully removed.'
  end


  private

  def set_product
    @product = Product.find(params[:id])
  end

  def safe_params
    params.require(:product).permit(:name, :description, :price_dollars)
  end

end

app/controllers/master/reports_controller.rb
class Master::ReportsController < MasterController

  def index
  end

  def pending_impressions
    @impressions = Impression.ordered.page(params[:page])
  end

end

app/controllers/master/searches_controller.rb
class Master::SearchesController < MasterController

  def index
    # Teachers
    @teachers = Teacher.all
    @teachers = @teachers.search(params[:search][:query]) if params[:search].try(:[], :query).present?
    if params[:search].try(:[], :sorty).present?
      @teachers = @teachers.sorty_order(params[:search][:sorty][:sort], sort_direction)
    else
      @teachers = @teachers.ordered
    end
    @teachers = @teachers.page(params[:teachers_page])

    # Schools
    @schools = School.all
    @schools = @schools.search(params[:search][:query]) if params[:search].try(:[], :query).present?
    if params[:search].try(:[], :sorty).present?
      @schools = @schools.sorty_order(sort_column, sort_direction)
    else
      @schools = @schools.ordered
    end
    @schools = @schools.page(params[:schools_page])
  end


  private

  def sort_column
    if params[:search].try(:[], :sorty).present?
      params[:search][:sorty][:sort]
    end
  end

end

app/controllers/master/sessions_controller.rb
class Master::SessionsController < ::Devise::SessionsController

  layout "master"
  # the rest is inherited, so it should work

end

app/controllers/master_controller.rb
class MasterController < ApplicationController

  layout 'master'

  before_action :authenticate_user!

end

app/views/master/teachers/_form.html.haml
= simple_form_for [@school, @teacher] do |f|
  = f.error_notification

  = f.input :prefix, as: :select, collection: Teacher::SUPERIORITY_PREFIXES, include_blank: 'Select Prefix'
  = f.input :first_name
  = f.input :last_name
  = f.input :email

  .form-group
    .col-sm-offset-2.col-sm-10
      = f.button :submit, class: 'btn btn-primary'
      = link_to 'Cancel', @teacher.new_record? ? school_teachers_path(@school) : school_teacher_path(@school, @teacher), class: 'btn btn-link'

app/views/master/teachers/_teachers_search_filter.html.haml
= simple_form_for :search, url: school_teachers_path(@school), method: :get, html: { id: "teachers_search_filter", class: "inline-search-form form form-inline" }, wrapper: :inline do |f|
  = f.input :query, as: :string, input_html: { value: (params[:search].try(:[], :query) if params[:search].present?), class: 'search-query', id: "inline_search" }, placeholder: "Search Term", autocomplete: 'off', label: false
  = f.simple_fields_for :sorty do |s|
    = s.input :direction, as: :hidden, input_html: { value: (params[:search][:sorty].try(:[], :direction) if params[:search].try(:[], :sorty).present?) } if params[:search].try(:[], :sorty).present?
    = s.input :sort, as: :hidden, input_html: { value: (params[:search][:sorty].try(:[], :sort) if params[:search].try(:[], :sorty).present?) } if params[:search].try(:[], :sorty).present?
  - if params[:search].present?
    = link_to school_teachers_path(@school), class: 'btn btn-danger', title: 'Clear Filter' do
      %span.glyphicon.glyphicon-remove

app/views/master/teachers/edit.html.haml
- title "Edit Teacher"

= render 'form'

app/views/master/teachers/index.html.haml
- title "#{@school.name} : Teachers", false

.page-header
  %h3.sub-title.inline
    #{@school.name} : Teachers
    %span
      = link_to district_school_path(@school.district, @school, anchor: 'general'), class: 'btn btn-default btn-xs', title: "Back to #{@school.name}" do
        %span.glyphicon.glyphicon-arrow-left

%ul.nav.nav-tabs
  %li
    = link_to district_school_path(@school.district, @school, anchor: 'general') do
      %span.glyphicon.glyphicon-file
      General
  %li.active
    = link_to '#teachers', data: {toggle: 'tab'} do
      %span.glyphicon.glyphicon-briefcase
      Teachers (#{@teachers.total_count})
  %li
    = link_to district_school_path(@school.district, @school, anchor: 'school_based_campaigns') do
      %span.glyphicon.glyphicon-fire
      School Based Campaigns (#{@school_based_campaigns.total_count})

= paginate @teachers

%div#button-toolbar
  = link_to new_school_teacher_path(@school), title: "New Teacher", class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
  = render "teachers_search_filter"

%table.table.table-striped.table-hover.table-condensed
  %thead
    %tr
      %th= Teacher.human_attribute_name(:prestigious_name)
      %th= sorty "last_name", Teacher.human_attribute_name(:last_name), {default: true}
      %th= sorty "first_name", Teacher.human_attribute_name(:first_name)
      %th= sorty "email", Teacher.human_attribute_name(:email)
      %th= sorty "prefix", Teacher.human_attribute_name(:prefix)
      %th= sorty "created_at", Teacher.human_attribute_name(:created_at)
      %th= sorty "updated_at", Teacher.human_attribute_name(:updated_at)
      %th
      %th
  %tbody
    - @teachers.each do |teacher|
      %tr
        %td= link_to teacher.prestigious_name, [teacher.school, teacher]
        %td= teacher.last_name
        %td= teacher.first_name
        %td= mail_to teacher.email
        %td= teacher.prefix
        %td= l(teacher.created_at, format: :short)
        %td= l(teacher.updated_at, format: :short)
        %td
          = link_to edit_school_teacher_path(teacher.school, teacher), class: 'btn btn-warning btn-xs', title: 'Edit Teacher' do
            %span.glyphicon.glyphicon-edit
        %td
          = link_to [teacher.school, teacher], method: :delete, data: { confirm: 'Are you sure?' }, id: "teacher_destroy_#{teacher.id}", title: "Remove Teacher", class: 'btn btn-danger btn-xs' do
            %span.glyphicon.glyphicon-remove

= paginate @teachers

app/views/master/teachers/new.html.haml
- title "New Teacher"

= render 'form'

app/views/master/teachers/reassign.html.haml
- title "Reassign Teacher"

%p.alert.alert-success
  The following Reassignment process will allow you to transfer one teacher
  and all their associated campaigns from one school into a different school.
  The appropriate States and Districts will automatically be updated.

= simple_form_for :reassign, url: reassign_school_teacher_path(@school, @teacher), html: { id: 'reassign_teacher' } do |f|
  = f.error_notification

  = f.input :state_id, as: :select, collection: State.ordered.map { |k| [k.name, k.id, {data: {abbr: k.abbr}}] }, include_blank: 'Select State', input_html: { data: {url: api_v1_districts_url} }
  = f.input :district_id, as: :select, collection: [], disabled: true, include_blank: 'Select District', input_html: { data: { url: api_v1_district_schools_url(district_id: ':district_id')}}
  = f.input :new_school_id, as: :select, collection: [], disabled: true, include_blank: 'Select New School', label: 'New School'

  .form-group
    .col-sm-offset-2.col-sm-10
      = f.button :submit, 'Reassign Teacher', class: 'btn btn-primary'
      = link_to 'Cancel', @teacher.new_record? ? school_teachers_path(@school) : school_teacher_path(@school, @teacher), class: 'btn btn-link'

app/views/master/teachers/show.html.haml
- title @teacher.prestigious_name, false

.page-header
  %h3.sub-title.inline
    = @teacher.prestigious_name
    %span
      = link_to school_teachers_path(@school), class: 'btn btn-default btn-xs', title: "Back to #{@school.name}" do
        %span.glyphicon.glyphicon-arrow-left

%ul.nav.nav-tabs
  %li.active
    = link_to '#general', data: {toggle: 'tab'} do
      %span.glyphicon.glyphicon-file
      General
  %li
    = link_to '#campaigns', data: {toggle: 'tab'} do
      %span.glyphicon.glyphicon-fire
      Teacher Based Campaigns (#{@campaigns.total_count})
  %li
    = link_to '#contributions', data: {toggle: 'tab'} do
      %span.glyphicon.glyphicon-briefcase
      Contributions (#{@contributions.total_count})

.tab-content
  #general.tab-pane.active
    %table.table.table-hover.table-striped.table-condensed
      %tbody
        %tr
          %th= Teacher.human_attribute_name(:full_name)
          %td
            = @teacher.full_name
            %span.pull-right
              = link_to edit_school_teacher_path(@school, @teacher), class: 'btn btn-warning btn-xs', title: "Edit Teacher" do
                %span.glyphicon.glyphicon-edit
                Edit
        %tr
          %th= Teacher.human_attribute_name(:email)
          %td= mail_to @teacher.email
        %tr
          %th= Teacher.human_attribute_name(:prefix)
          %td= @teacher.prefix
        %tr
          %th= Teacher.human_attribute_name(:first_name)
          %td= @teacher.first_name
        %tr
          %th= Teacher.human_attribute_name(:last_name)
          %td= @teacher.last_name
        %tr
          %th= Teacher.human_attribute_name(:prestigious_name)
          %td= @teacher.prestigious_name
        %tr
          %th= Teacher.human_attribute_name(:school)
          %td= link_to @teacher.school.name, [@teacher.school.district, @teacher.school]
        %tr
          %th= Teacher.human_attribute_name(:created_at)
          %td= l(@teacher.created_at, format: :short)
        %tr
          %th= Teacher.human_attribute_name(:updated_at)
          %td= l(@teacher.updated_at, format: :short)
        %tr
          %th Actions
          %td
            = link_to reassign_school_teacher_path(@school, @teacher), class: 'btn btn-info btn-xs', title: "Reassign Teacher" do
              %span.glyphicon.glyphicon-shuffle
              Reassign Teacher

  #campaigns.tab-pane
    %div#button-toolbar
      = link_to new_master_ajax_teacher_campaign_path(@teacher), id: 'new_teacher_campaign_link', class: 'btn btn-primary', role: "button", data: {toggle: "modal", target: '#newCampaignModal', remote: true}, title: "Add New Teacher Campaign" do
        %span.glyphicon.glyphicon-plus

    = paginate @campaigns, param_name: "campaigns_page", params: { anchor: "campaigns" }
    %table.table.table-striped.table-hover.table-condensed#teacher_based_campaigns_table
      %thead
        %tr
          %th= Campaign.human_attribute_name(:name)
          %th= Campaign.human_attribute_name(:school)
          %th= Campaign.human_attribute_name(:school_wide)
          %th= Campaign.human_attribute_name(:active)
      %tbody
        - @campaigns.each do |campaign|
          %tr
            %td= link_to campaign.name, campaign
            %td= link_to campaign.school.name, [campaign.school.district, campaign.school]
            %td= campaign.school_wide? ? "Yes" : "No"
            %td= campaign.active? ? "Yes" : "No"

  #contributions.tab-pane
    = paginate @contributions, param_name: "contributions_page", params: { anchor: "contributions" }
    %table.table.table-striped.table-hover.table-condensed
      %thead
        %tr
          %th= Contribution.human_attribute_name(:pledge_id)
          %th= Contribution.human_attribute_name(:amount)
          %th= Contribution.human_attribute_name(:contributor)
          %th= Contribution.human_attribute_name(:pledged_at)
      %tbody
        - @contributions.each do |contribution|
          %tr
            %td= link_to contribution.pledge_id, contribution
            %td= humanized_money_with_symbol(contribution.amount.dollars, no_cents_if_whole: false)
            %td= link_to contribution.contributor.name, contribution.contributor
            %td
              - if contribution.pledged_at.present?
                = l(contribution.pledged_at, format: :short)
              - else
                N/A

.modal.fade#newCampaignModal
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} &times;
        %h3.modal-title
      .modal-body
        %p