config/routes.rb
Rails.application.routes.draw do

  namespace :api, path: "api" do
    namespace :v1 do
      resources :districts, only: [:index] do
        resources :schools, only: [:index] do
          resources :campaigns, only: [:index]
        end
      end
      resources :schools, only: [] do
        resources :teachers, only: [:index]
      end
    end
  end

  constraints(subdomain: /master/) do
    devise_for :users, path: 'u', controllers: { sessions: "master/sessions" }

    namespace :master_ajax do
      resources :schools, only: [] do
        resources :campaigns, only: [:new, :create], to: 'schools/campaigns'
      end

      resources :teachers, only: [] do
        resources :campaigns, only: [:new, :create], to: 'teachers/campaigns'
      end
    end

    scope module: 'master' do
      resources :users
      resources :products

      resources :states do
        resources :districts
      end

      resources :districts, only: [] do
        resources :schools
      end

      resources :schools do
        resources :teachers do
          member do
            match :reassign, via: [:get, :post]
          end
        end
      end

      resources :campaigns, param: 'slug', except: [:new, :create] do
        resources :impressions
      end

      resources :imports, only: [] do
        collection do
          match :schools, via: [:get, :post]
          match :indiegogo, via: [:get, :post]
        end
      end

      resources :contributors
      resources :contributions
      resource :tos, only: [:show, :edit, :update]

      resources :searches, only: [:index]

      resources :reports, only: [:index] do
        collection do
          match :pending_impressions, via: [:get]
        end
      end

      resources :campaign_requests, except: [:new, :create], param: 'slug' do
        member do
          match :convert, via: [:get, :post]
        end
      end

      match '/', to: 'campaigns#index', via: [:get], as: :master_root
    end
  end

  constraints(subdomain: /landing/) do
    resources :schools, only: [] do
      resources :teachers, only: [:new, :create]
    end

    resources :campaigns, only: [], param: 'slug' do
      collection do
        match :new, via: [:get], as: :landing_new, path: 'new'
        match :create, via: [:post]
      end
      member do
        match :show, via: [:get], as: :landing
        match :partner, via: [:get]
        match :reports, via: [:get]
        match :contributions, via: [:get]
        match :thank_you, via: [:get, :post]
      end
      resources :impressions, only: [:create], as: :landing_impressions
    end

    resources :campaign_requests, only: [:new, :create], param: 'slug'
    resources :campaign_requests, only: [], param: 'slug' do
      member do
        match :show, via: [:get], as: :landing
      end
    end
  end

  root 'public#index'

end

app/controllers/master/campaign_requests_controller.rb
class Master::CampaignRequestsController < MasterController

  before_action :set_campaign_request, only: [:show, :edit, :update, :destroy, :convert]
  before_action :check_approved_at, only: [:edit, :update, :convert]

  def index
    @campaign_requests = CampaignRequest.not_approved.ordered.page(params[:page])
  end

  def show
  end

  def edit
  end

  def update
    if @campaign_request.update(safe_params)
      redirect_to @campaign_request, notice: 'Campaign Request was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @campaign_request.destroy
    redirect_to campaign_requests_url, notice: 'Campaign Request was successfully removed.'
  end

  def convert
    if request.post?
      if @campaign_request.convert(convert_params)
        redirect_to campaign_requests_url, notice: 'Campaign Request was successfully converted.'
      else
        render :convert
      end
    else
      # GET stuff here
    end
  end


  private

  def check_approved_at
    if @campaign_request.approved_at.present?
      flash[:error] = 'Cannot modify approved Campaign Requests!'
      redirect_to campaign_requests_path
    end
  end

  def set_campaign_request
    @campaign_request = CampaignRequest.find_by(slug: params[:slug])
  end

  def safe_params
    safe_attributes = [
      :campaign_name,
      :district_name,
      :email,
      :physical_address,
      :physical_address_ext,
      :physical_city,
      :physical_postal_code,
      :physical_state,
      :product_id,
      :school_name,
      :school_wide,
      :state_id,
      :teacher_first_name,
      :teacher_last_name,
    ]
    params.require(:campaign_request).permit(safe_attributes)
  end

  def convert_params
    safe_attributes = [
      :campaign_name,
      :district_name,
      :email,
      :physical_address,
      :physical_address_ext,
      :physical_city,
      :physical_postal_code,
      :physical_state,
      :product_id,
      :school_name,
      :school_wide,
      :state_id,
      :teacher_first_name,
      :teacher_last_name,
      associations: [
        :district_id,
        :school_id,
        :teacher_id,
      ]
    ]
    params.require(:convert_campaign_request).permit(safe_attributes)
  end

end

app/controllers/master/campaigns_controller.rb
class Master::CampaignsController < MasterController
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]

  def index
    @campaigns = Campaign.all
    @teacher_campaigns = @campaigns.teacher_based
    @school_campaigns = @campaigns.school_based

    # Search based on my criteria
    if params[:search].try(:[], :query).present?
      @teacher_campaigns = @teacher_campaigns.search(params[:search][:query])
      @school_campaigns = @school_campaigns.search(params[:search][:query])
    end

    # Order by Sorty Params
    if params[:search].try(:[], :sorty).present?
      @teacher_campaigns = @teacher_campaigns.sorty_order(sort_column, sort_direction)
      @school_campaigns = @school_campaigns.sorty_order(sort_column, sort_direction)
    else
      @teacher_campaigns = @teacher_campaigns.ordered
      @school_campaigns = @school_campaigns.ordered
    end

    # Paginate them
    @teacher_campaigns = @teacher_campaigns.page(params[:teachers_page])
    @school_campaigns = @school_campaigns.page(params[:schools_page])
  end

  def show
    @contributions = @campaign.contributions.ordered.page(params[:contributions_page])
    @impressions = @campaign.impressions.ordered.page(params[:impressions_page])
  end

  def edit
  end

  def update
    if @campaign.update(safe_params)
      redirect_to @campaign, notice: 'Campaign was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @campaign.destroy
    redirect_to campaigns_url, notice: 'Campaign was successfully removed.'
  end


  private

  def set_campaign
    @campaign = Campaign.find_by(slug: params[:slug])
  end

  def safe_params
    safe_attributes = [
      :active,
      :campaignable_id,
      :campaignable_type,
      :district_id,
      :goal_amount_dollars,
      :name,
      :product_id,
      :school_id,
      :state_id,
      :physical_address,
      :physical_address_ext,
      :physical_city,
      :physical_state,
      :physical_postal_code,
    ]
    params.require(:campaign).permit(safe_attributes)
  end

end

app/controllers/master/contributions_controller.rb
class Master::ContributionsController < MasterController
  before_action :set_contribution, only: [:show, :edit, :update, :destroy]

  def index
    @contributions = Contribution.all
    @contributions = @contributions.search(params[:search][:query]) if params[:search].try(:[], :query).present?
    if params[:search].try(:[], :sorty).present?
      @contributions = @contributions.sorty_order(sort_column, sort_direction)
    else
      @contributions = @contributions.ordered
    end
    @contributions = @contributions.page(params[:page])
  end

  def show
  end

  def new
    @contribution = Contribution.new
  end

  def edit
  end

  def create
    @contribution = Contribution.new(safe_params)

    if @contribution.save
      redirect_to @contribution, notice: 'Contribution was successfully created.'
    else
      render :new
    end
  end

  def update
    if @contribution.update(safe_params)
      redirect_to @contribution, notice: 'Contribution was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @contribution.destroy
    redirect_to contributions_url, notice: 'Contribution was successfully removed.'
  end


  private

  def set_contribution
    @contribution = Contribution.find(params[:id])
  end

  def safe_params
    params.require(:contribution).permit(:pledge_id, :pledged_at, :contributor_id, :campaign_id, :amount_dollars)
  end

end

app/controllers/master/contributors_controller.rb
class Master::ContributorsController < MasterController
  before_action :set_contributor, only: [:show, :edit, :update, :destroy]

  def index
    @contributors = Contributor.all
    @contributors = @contributors.search(params[:search][:query]) if params[:search].try(:[], :query).present?
    if params[:search].try(:[], :sorty).present?
      @contributors = @contributors.sorty_order(sort_column, sort_direction)
    else
      @contributors = @contributors.ordered
    end
    @contributors = @contributors.page(params[:page])
  end

  def show
    @contributions = @contributor.contributions.ordered.page(params[:page])
  end

  def new
    @contributor = Contributor.new
  end

  def edit
  end

  def create
    @contributor = Contributor.new(contributor_params)

    if @contributor.save
      redirect_to @contributor, notice: 'Contributor was successfully created.'
    else
      render :new
    end
  end

  def update
    if @contributor.update(contributor_params)
      redirect_to @contributor, notice: 'Contributor was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @contributor.destroy
    redirect_to contributors_url, notice: 'Contributor was successfully removed.'
  end


  private

  def set_contributor
    @contributor = Contributor.find(params[:id])
  end

  def contributor_params
    params.require(:contributor).permit(:name, :email)
  end

end

app/controllers/master/districts_controller.rb
class Master::DistrictsController < MasterController
  before_action :set_state
  before_action :set_district, only: [:show, :edit, :update, :destroy]

  def index
    @districts = @state.districts
    @districts = @districts.search(params[:search][:query]) if params[:search].try(:[], :query).present?
    if params[:search].try(:[], :sorty).present?
      @districts = @districts.sorty_order(sort_column, sort_direction)
    else
      @districts = @districts.ordered
    end
    @districts = @districts.page(params[:page])
    @campaigns = @state.campaigns.ordered.page(params[:campaigns_page])
  end

  def show
    @schools = @district.schools.ordered.page(params[:schools_page])
    @campaigns = @district.campaigns.ordered.page(params[:campaigns_page])
  end

  def new
    @district = @state.districts.new
  end

  def edit
  end

  def create
    @district = @state.districts.new(safe_params)

    if @district.save
      redirect_to state_district_url(@state, @district), notice: 'District was successfully created.'
    else
      render :new
    end
  end

  def update
    if @district.update(safe_params)
      redirect_to state_district_url(@state, @district), notice: 'District was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @district.destroy
    redirect_to state_districts_url(@state), notice: 'District was successfully removed.'
  end


  private

  def set_state
    @state = State.find_by(abbr: params[:state_id])
  end

  def set_district
    @district = @state.districts.find(params[:id])
  end

  def safe_params
    params.require(:district).permit(:name, :state_id)
  end

end

app/controllers/master/imports_controller.rb
class Master::ImportsController < MasterController

  def schools
    if request.post?
      result = Import.import_schools(safe_params.try(:[], :file))
      if result[:success]
        flash[:notice] = "Successfully imported stuff, count: #{result.try(:[], :count)}"
      else
        flash[:error] = "Failed to import: #{result.try(:[], :message)}"
      end
      redirect_to schools_imports_url
    else
      # GET stuff here
    end
  end

  def indiegogo
    if request.post?
      result = Import.import_indiegogo_data(safe_params.try(:[], :file))
      if result[:success]
        flash[:notice] = "Successfully imported indiegogo data, count: #{result.try(:[], :count)}"
      else
        flash[:error] = "Failed to import: #{result.try(:[], :message)}"
      end
      redirect_to indiegogo_imports_url
    else
      # GET stuff here
    end
  end


  private

  def safe_params
    safe_attributes = [:file]
    params.require(:imports).permit(safe_attributes)
  end

end

app/controllers/master/impressions_controller.rb
class Master::ImpressionsController < MasterController
  before_action :set_campaign
  before_action :set_impression, only: [:show, :edit, :update, :destroy]

  def index
    @impressions = @campaign.impressions.ordered.page(params[:page])
    @contributions = @campaign.contributions.ordered.page(params[:contributions_page])
  end

  def show
  end

  def new
    @impression = @campaign.impressions.new
  end

  def edit
  end

  def create
    @impression = @campaign.impressions.new(safe_params)

    if @impression.save
      redirect_to campaign_impressions_url(@campaign.to_param), notice: 'Impression was successfully created.'
    else
      render :new
    end
  end

  def update
    if @impression.update(safe_params)
      redirect_to campaign_impressions_url(@campaign.to_param), notice: 'Impression was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @impression.destroy
    redirect_to campaign_impressions_url(@campaign.to_param), notice: 'Impression was successfully removed.'
  end


  private

  def set_campaign
    @campaign = Campaign.find_by(slug: params[:campaign_slug])
  end

  def set_impression
    @impression = @campaign.impressions.find(params[:id])
  end

  def safe_params
    safe_attributes = [:email, :campaign_id, :referral_kind, :token]
    params.require(:impression).permit(safe_attributes)
  end

end

app/controllers/master/products_controller.rb
class Master::ProductsController < MasterController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
    @products = @products.search(params[:search][:query]) if params[:search].try(:[], :query).present?
    if params[:search].try(:[], :sorty).present?
      @products = @products.sorty_order(sort_column, sort_direction)
    else
      @products = @products.ordered
    end
    @products = @products.page(params[:page])
  end

  def show
    @campaigns = @product.campaigns.ordered.page(params[:campaigns_page])
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(safe_params)

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  def update
    if @product.update(safe_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully removed.'
  end


  private

  def set_product
    @product = Product.find(params[:id])
  end

  def safe_params
    params.require(:product).permit(:name, :description, :price_dollars)
  end

end

app/controllers/master/reports_controller.rb
class Master::ReportsController < MasterController

  def index
  end

  def pending_impressions
    @impressions = Impression.ordered.page(params[:page])
  end

end

app/controllers/master/schools_controller.rb
class Master::SchoolsController < MasterController
  before_action :set_district
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  def index
    @schools = @district.schools
    @schools = @schools.search(params[:search][:query]) if params[:search].try(:[], :query).present?
    if params[:search].try(:[], :sorty).present?
      @schools = @schools.sorty_order(sort_column, sort_direction)
    else
      @schools = @schools.ordered
    end
    @schools = @schools.page(params[:page])
    @campaigns = @district.campaigns.ordered.page(params[:campaigns_page])
  end

  def show
    @teachers = @school.teachers.ordered.page(params[:teachers_page])
    @school_based_campaigns = @school.school_wide_campaigns.ordered.page(params[:campaigns_page])
  end

  def new
    @school = @district.schools.new
  end

  def edit
  end

  def create
    @school = @district.schools.new(safe_params)

    if @school.save
      redirect_to district_school_url(@district, @school), notice: 'School was successfully created.'
    else
      render :new
    end
  end

  def update
    if @school.update(safe_params)
      redirect_to district_school_url(@district, @school), notice: 'School was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @school.destroy
    redirect_to district_schools_url(@district), notice: 'School was successfully removed.'
  end


  private

  def set_district
    @district = District.find(params[:district_id])
  end

  def set_school
    @school = @district.schools.find(params[:id])
  end

  def safe_params
    params.require(:school).permit(:name)
  end

end

app/controllers/master/sessions_controller.rb
class Master::SessionsController < ::Devise::SessionsController

  layout "master"
  # the rest is inherited, so it should work

end

app/controllers/master_controller.rb
class MasterController < ApplicationController

  layout 'master'

  before_action :authenticate_user!

end

app/views/master/contributions/_contributions_search_filter.html.haml
= simple_form_for :search, url: contributions_path, method: :get, html: { id: "contributions_search_filter", class: "inline-search-form form form-inline" }, wrapper: :inline do |f|
  = f.input :query, as: :string, input_html: { value: (params[:search].try(:[], :query) if params[:search].present?), class: 'search-query', id: "inline_search" }, placeholder: "Search Term", autocomplete: 'off', label: false
  = f.simple_fields_for :sorty do |s|
    = s.input :direction, as: :hidden, input_html: { value: (params[:search][:sorty].try(:[], :direction) if params[:search].try(:[], :sorty).present?) } if params[:search].try(:[], :sorty).present?
    = s.input :sort, as: :hidden, input_html: { value: (params[:search][:sorty].try(:[], :sort) if params[:search].try(:[], :sorty).present?) } if params[:search].try(:[], :sorty).present?
  - if params[:search].present?
    = link_to contributions_path, class: 'btn btn-danger', title: 'Clear Filter' do
      %span.glyphicon.glyphicon-remove

app/views/master/contributions/_form.html.haml
= simple_form_for(@contribution) do |f|
  = f.error_notification

  = f.input :pledge_id, as: :string
  = f.input :pledged_at, as: :string, input_html: { class: 'datepicker' }
  = f.association :contributor, include_blank: false
  = f.association :campaign, include_blank: false
  = f.input :amount_dollars, required: true do
    = f.input_field :amount_dollars, value: @contribution.new_record? ? number_with_precision(1.00, precision: 2) : number_with_precision(@contribution.amount.dollars, precision: 2), class: "amount-dollars", as: :string

  .form-group
    .col-sm-offset-2.col-sm-10
      = f.button :submit, class: 'btn btn-primary'
      = link_to 'Cancel', contributions_path, class: 'btn btn-link'

app/views/master/contributions/edit.html.haml
- title "Edit Contribution"

= render 'form'

app/views/master/contributions/index.html.haml
- title "Contributions"

- content_for(:toolbar) do
  = link_to new_contribution_path, title: "New Contribution", class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
  = render "contributions_search_filter"

= paginate @contributions

%table.table.table-striped.table-hover.table-condensed
  %thead
    %tr
      %th= sorty "amount_cents", Contribution.human_attribute_name(:amount)
      %th= sorty "contributor", Contribution.human_attribute_name(:contributor)
      %th= sorty "campaign", Contribution.human_attribute_name(:campaign)
      %th= sorty "pledge_id", Contribution.human_attribute_name(:pledge_id), {default: true}
      %th= sorty "pledged_at", Contribution.human_attribute_name(:pledged_at)
      %th= Contribution.human_attribute_name(:impression_token)
      %th= sorty "imported_at", Contribution.human_attribute_name(:imported_at)
      %th
      %th
  %tbody
    - @contributions.each do |contribution|
      %tr
        %td= link_to(humanized_money_with_symbol(contribution.amount.dollars, no_cents_if_whole: false), contribution)
        %td
          - if contribution.contributor.present?
            = link_to contribution.contributor.name, contribution.contributor
          - else
            N/A
        %td
          - if contribution.campaign.present?
            = link_to contribution.campaign.name, contribution.campaign
          - else
            N/A
        %td= link_to contribution.pledge_id, contribution
        %td
          - if contribution.pledged_at.present?
            = l(contribution.pledged_at, format: :short)
          - else
            N/A
        %td= contribution.impression_token
        %td
          - if contribution.imported_at.present?
            = l(contribution.imported_at, format: :short)
          - else
            N/A
        %td
          = link_to edit_contribution_path(contribution), class: 'btn btn-warning btn-xs', title: 'Edit Contribution' do
            %span.glyphicon.glyphicon-edit
        %td
          = link_to contribution, method: :delete, data: { confirm: 'Are you sure?' }, id: "contribution_destroy_#{contribution.id}", title: "Remove Contribution", class: 'btn btn-danger btn-xs' do
            %span.glyphicon.glyphicon-remove

= paginate @contributions

app/views/master/contributions/new.html.haml
- title "New Contribution"

= render 'form'

app/views/master/contributions/show.html.haml
- title "Contribution : #{@contribution.pledge_id}", false

.page-header
  %h3.sub-title.inline
    Contribution : #{@contribution.pledge_id}
    %span
      = link_to edit_contribution_path(@contribution), class: 'btn btn-warning btn-xs', title: "Edit Contribution" do
        %span.glyphicon.glyphicon-edit

%h5.page-header General Information
%table.table.table-hover.table-striped.table-condensed
  %tbody
    %tr
      %th= Contribution.human_attribute_name(:pledge_id)
      %td= @contribution.pledge_id
    %tr
      %th= Contribution.human_attribute_name(:pledged_at)
      %td
        - if @contribution.pledged_at.present?
          = l(@contribution.pledged_at, format: :short)
        - else
          N/A
    %tr
      %th= Contribution.human_attribute_name(:contributor)
      %td
        - if @contribution.contributor.present?
          = link_to @contribution.contributor.name, @contribution.contributor
        - else
          N/A
    %tr
      %th= Contribution.human_attribute_name(:campaign)
      %td
        - if @contribution.campaign.present?
          = link_to @contribution.campaign.name, @contribution.campaign
        - else
          N/A
    %tr
      %th= Contribution.human_attribute_name(:amount)
      %td= humanized_money_with_symbol(@contribution.amount.dollars, no_cents_if_whole: false)
    %tr
      %th= Contribution.human_attribute_name(:created_at)
      %td= l(@contribution.created_at, format: :short)
    %tr
      %th= Contribution.human_attribute_name(:updated_at)
      %td= l(@contribution.updated_at, format: :short)